parquet_path: ./output/pdf_page_objects.parquet

milvus:
    db_path: /mloscratch/users/zablocki/clicolpali/milvus_data.db
    collection_name: pdf_pages
    create_collection: true
    dim: 128
    metric_type: IP
