db_path: ./output/milvus_data.db
collection_name: "pdf_pages"

model_name: "vidore/colpali-v1.3"
top_k: 3
dim: 128
metric_type: "IP"
max_workers: 16
text_parquet_path: "./output/pdf_page_text.parquet"

