input_path: examples/sample_data
output_path: examples/mmore_output_fast/

use_fast_processors: true
extract_images: true
distributed: false
scheduler_file: scheduler-file.json

batch_sizes:
  PDFProcessor: 4000
