rag:
  retriever:
    db:
      uri: ./proc_demo.db
      name: my_db
    hybrid_search_weight: 0.5
    k: 4
    use_web: false
  llm:
    llm_name: OpenMeditron/meditron3-8b
    base_url: null
    organization: HF
    max_new_tokens: 250
    temperature: 0.7
  system_prompt: "Use the following context to answer the questions.\n\nContext:\n{context}"
mode: local
mode_args: null
