name: ðŸ§ª PyTest unit tests

on:
    push:
        branches:
        - master
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.x"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv and create venv
        run: |
          pipx install uv
          uv venv .venv

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (using uv)
        run: |
          source .venv/bin/activate
          uv pip install -e .[rag,dev]

      - name: Show installed cohere and langchain-cohere versions
        run: |
          source .venv/bin/activate
          uv pip show cohere || echo "Cohere not installed"
          uv pip show langchain-cohere || echo "Langchain-cohere not installed"

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
